// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT id, user_id, company_name, full_name, phone, address_line1, address_line2, city, state, postal_code, country, tax_id, created_at, updated_at FROM customer_profiles WHERE user_id = $1
`

func (q *Queries) GetCustomerProfile(ctx context.Context, userID uuid.UUID) (CustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, userID)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.FullName,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.TaxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCustomerProfile = `-- name: UpsertCustomerProfile :one
INSERT INTO customer_profiles (user_id, full_name, company_name, phone, address_line1, address_line2, city, state, postal_code, country, tax_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    company_name = EXCLUDED.company_name,
    phone = EXCLUDED.phone,
    address_line1 = EXCLUDED.address_line1,
    address_line2 = EXCLUDED.address_line2,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    postal_code = EXCLUDED.postal_code,
    country = EXCLUDED.country,
    tax_id = EXCLUDED.tax_id,
    updated_at = NOW()
RETURNING id, user_id, company_name, full_name, phone, address_line1, address_line2, city, state, postal_code, country, tax_id, created_at, updated_at
`

type UpsertCustomerProfileParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	FullName     pgtype.Text `json:"full_name"`
	CompanyName  pgtype.Text `json:"company_name"`
	Phone        pgtype.Text `json:"phone"`
	AddressLine1 pgtype.Text `json:"address_line1"`
	AddressLine2 pgtype.Text `json:"address_line2"`
	City         pgtype.Text `json:"city"`
	State        pgtype.Text `json:"state"`
	PostalCode   pgtype.Text `json:"postal_code"`
	Country      pgtype.Text `json:"country"`
	TaxID        pgtype.Text `json:"tax_id"`
}

func (q *Queries) UpsertCustomerProfile(ctx context.Context, arg UpsertCustomerProfileParams) (CustomerProfile, error) {
	row := q.db.QueryRow(ctx, upsertCustomerProfile,
		arg.UserID,
		arg.FullName,
		arg.CompanyName,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.TaxID,
	)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.FullName,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.TaxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
