// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date)
VALUES ($1, $2, $3, 'draft', $4, $5, $6, $7, $8)
RETURNING id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	UserID        uuid.UUID          `json:"user_id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	Tax           pgtype.Numeric     `json:"tax"`
	Total         pgtype.Numeric     `json:"total"`
	Currency      string             `json:"currency"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.UserID,
		arg.OrderID,
		arg.InvoiceNumber,
		arg.Subtotal,
		arg.Tax,
		arg.Total,
		arg.Currency,
		arg.DueDate,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.Currency,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (invoice_id, description, quantity, unit_price, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, description, quantity, unit_price, amount, created_at
`

type CreateInvoiceItemParams struct {
	InvoiceID   uuid.UUID      `json:"invoice_id"`
	Description string         `json:"description"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Amount      pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.Amount,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.Currency,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.Currency,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllInvoices = `-- name: ListAllInvoices :many
SELECT id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at FROM invoices ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllInvoices(ctx context.Context, arg ListAllInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listAllInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderID,
			&i.InvoiceNumber,
			&i.Status,
			&i.Subtotal,
			&i.Tax,
			&i.Total,
			&i.Currency,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, description, quantity, unit_price, amount, created_at FROM invoice_items WHERE invoice_id = $1
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByUser = `-- name: ListInvoicesByUser :many
SELECT id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at FROM invoices WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListInvoicesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListInvoicesByUser(ctx context.Context, arg ListInvoicesByUserParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderID,
			&i.InvoiceNumber,
			&i.Status,
			&i.Subtotal,
			&i.Tax,
			&i.Total,
			&i.Currency,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :one
UPDATE invoices SET status = 'paid', paid_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at
`

func (q *Queries) MarkInvoicePaid(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, markInvoicePaid, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.Currency,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, order_id, invoice_number, status, subtotal, tax, total, currency, due_date, paid_at, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status InvoiceStatus `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.Currency,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
