// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM payments
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7)
RETURNING id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID                  uuid.UUID      `json:"user_id"`
	InvoiceID               pgtype.UUID    `json:"invoice_id"`
	StripePaymentIntentID   pgtype.Text    `json:"stripe_payment_intent_id"`
	StripeCheckoutSessionID pgtype.Text    `json:"stripe_checkout_session_id"`
	Amount                  pgtype.Numeric `json:"amount"`
	Currency                string         `json:"currency"`
	Method                  pgtype.Text    `json:"method"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.InvoiceID,
		arg.StripePaymentIntentID,
		arg.StripeCheckoutSessionID,
		arg.Amount,
		arg.Currency,
		arg.Method,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceID,
		&i.StripePaymentIntentID,
		&i.StripeCheckoutSessionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentEvent = `-- name: CreatePaymentEvent :one
INSERT INTO payment_events (stripe_event_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, stripe_event_id, event_type, payload, processed, error_message, created_at, processed_at
`

type CreatePaymentEventParams struct {
	StripeEventID string `json:"stripe_event_id"`
	EventType     string `json:"event_type"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, createPaymentEvent, arg.StripeEventID, arg.EventType, arg.Payload)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceID,
		&i.StripePaymentIntentID,
		&i.StripeCheckoutSessionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByStripeIntent = `-- name: GetPaymentByStripeIntent :one
SELECT id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at FROM payments WHERE stripe_payment_intent_id = $1
`

func (q *Queries) GetPaymentByStripeIntent(ctx context.Context, stripePaymentIntentID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByStripeIntent, stripePaymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceID,
		&i.StripePaymentIntentID,
		&i.StripeCheckoutSessionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByStripeSession = `-- name: GetPaymentByStripeSession :one
SELECT id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at FROM payments WHERE stripe_checkout_session_id = $1
`

func (q *Queries) GetPaymentByStripeSession(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByStripeSession, stripeCheckoutSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceID,
		&i.StripePaymentIntentID,
		&i.StripeCheckoutSessionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentEventByStripeID = `-- name: GetPaymentEventByStripeID :one
SELECT id, stripe_event_id, event_type, payload, processed, error_message, created_at, processed_at FROM payment_events WHERE stripe_event_id = $1
`

func (q *Queries) GetPaymentEventByStripeID(ctx context.Context, stripeEventID string) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentEventByStripeID, stripeEventID)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at FROM payments ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listAllPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvoiceID,
			&i.StripePaymentIntentID,
			&i.StripeCheckoutSessionID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Method,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at FROM payments WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPaymentsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvoiceID,
			&i.StripePaymentIntentID,
			&i.StripeCheckoutSessionID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Method,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentEventFailed = `-- name: MarkPaymentEventFailed :exec
UPDATE payment_events SET processed = true, error_message = $2, processed_at = NOW() WHERE id = $1
`

type MarkPaymentEventFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkPaymentEventFailed(ctx context.Context, arg MarkPaymentEventFailedParams) error {
	_, err := q.db.Exec(ctx, markPaymentEventFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markPaymentEventProcessed = `-- name: MarkPaymentEventProcessed :exec
UPDATE payment_events SET processed = true, processed_at = NOW() WHERE id = $1
`

func (q *Queries) MarkPaymentEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentEventProcessed, id)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, invoice_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, method, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status PaymentStatus `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceID,
		&i.StripePaymentIntentID,
		&i.StripeCheckoutSessionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
