// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features, created_at, updated_at
`

type CreatePlanParams struct {
	ProductID      uuid.UUID       `json:"product_id"`
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	Description    pgtype.Text     `json:"description"`
	CpuCores       pgtype.Int4     `json:"cpu_cores"`
	MemoryMb       pgtype.Int4     `json:"memory_mb"`
	DiskGb         pgtype.Int4     `json:"disk_gb"`
	BandwidthTb    pgtype.Numeric  `json:"bandwidth_tb"`
	PriceMonthly   pgtype.Numeric  `json:"price_monthly"`
	PriceQuarterly pgtype.Numeric  `json:"price_quarterly"`
	PriceAnnually  pgtype.Numeric  `json:"price_annually"`
	SetupFee       pgtype.Numeric  `json:"setup_fee"`
	IsActive       bool            `json:"is_active"`
	SortOrder      int32           `json:"sort_order"`
	Features       json.RawMessage `json:"features"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ProductID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.BandwidthTb,
		arg.PriceMonthly,
		arg.PriceQuarterly,
		arg.PriceAnnually,
		arg.SetupFee,
		arg.IsActive,
		arg.SortOrder,
		arg.Features,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.BandwidthTb,
		&i.PriceMonthly,
		&i.PriceQuarterly,
		&i.PriceAnnually,
		&i.SetupFee,
		&i.IsActive,
		&i.SortOrder,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.BandwidthTb,
		&i.PriceMonthly,
		&i.PriceQuarterly,
		&i.PriceAnnually,
		&i.SetupFee,
		&i.IsActive,
		&i.SortOrder,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanBySlug = `-- name: GetPlanBySlug :one
SELECT id, product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features, created_at, updated_at FROM plans WHERE slug = $1
`

func (q *Queries) GetPlanBySlug(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanBySlug, slug)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.BandwidthTb,
		&i.PriceMonthly,
		&i.PriceQuarterly,
		&i.PriceAnnually,
		&i.SetupFee,
		&i.IsActive,
		&i.SortOrder,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features, created_at, updated_at FROM plans ORDER BY sort_order ASC, created_at DESC LIMIT $1 OFFSET $2
`

type ListAllPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllPlans(ctx context.Context, arg ListAllPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listAllPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.BandwidthTb,
			&i.PriceMonthly,
			&i.PriceQuarterly,
			&i.PriceAnnually,
			&i.SetupFee,
			&i.IsActive,
			&i.SortOrder,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByProduct = `-- name: ListPlansByProduct :many
SELECT id, product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features, created_at, updated_at FROM plans WHERE product_id = $1 AND is_active = true ORDER BY sort_order ASC, price_monthly ASC
`

func (q *Queries) ListPlansByProduct(ctx context.Context, productID uuid.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.BandwidthTb,
			&i.PriceMonthly,
			&i.PriceQuarterly,
			&i.PriceAnnually,
			&i.SetupFee,
			&i.IsActive,
			&i.SortOrder,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    cpu_cores = COALESCE($5, cpu_cores),
    memory_mb = COALESCE($6, memory_mb),
    disk_gb = COALESCE($7, disk_gb),
    bandwidth_tb = COALESCE($8, bandwidth_tb),
    price_monthly = COALESCE($9, price_monthly),
    price_quarterly = COALESCE($10, price_quarterly),
    price_annually = COALESCE($11, price_annually),
    setup_fee = COALESCE($12, setup_fee),
    is_active = COALESCE($13, is_active),
    sort_order = COALESCE($14, sort_order),
    features = COALESCE($15, features),
    updated_at = NOW()
WHERE id = $1
RETURNING id, product_id, name, slug, description, cpu_cores, memory_mb, disk_gb, bandwidth_tb, price_monthly, price_quarterly, price_annually, setup_fee, is_active, sort_order, features, created_at, updated_at
`

type UpdatePlanParams struct {
	ID             uuid.UUID       `json:"id"`
	Name           pgtype.Text     `json:"name"`
	Slug           pgtype.Text     `json:"slug"`
	Description    pgtype.Text     `json:"description"`
	CpuCores       pgtype.Int4     `json:"cpu_cores"`
	MemoryMb       pgtype.Int4     `json:"memory_mb"`
	DiskGb         pgtype.Int4     `json:"disk_gb"`
	BandwidthTb    pgtype.Numeric  `json:"bandwidth_tb"`
	PriceMonthly   pgtype.Numeric  `json:"price_monthly"`
	PriceQuarterly pgtype.Numeric  `json:"price_quarterly"`
	PriceAnnually  pgtype.Numeric  `json:"price_annually"`
	SetupFee       pgtype.Numeric  `json:"setup_fee"`
	IsActive       pgtype.Bool     `json:"is_active"`
	SortOrder      pgtype.Int4     `json:"sort_order"`
	Features       json.RawMessage `json:"features"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.BandwidthTb,
		arg.PriceMonthly,
		arg.PriceQuarterly,
		arg.PriceAnnually,
		arg.SetupFee,
		arg.IsActive,
		arg.SortOrder,
		arg.Features,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.BandwidthTb,
		&i.PriceMonthly,
		&i.PriceQuarterly,
		&i.PriceAnnually,
		&i.SetupFee,
		&i.IsActive,
		&i.SortOrder,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
