// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelService(ctx context.Context, id uuid.UUID) error
	CompleteJob(ctx context.Context, id uuid.UUID) (ProvisioningJob, error)
	CountInvoices(ctx context.Context) (int64, error)
	CountOrders(ctx context.Context) (int64, error)
	CountOrdersByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPayments(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountServicesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentEvent, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProvisioningJob(ctx context.Context, arg CreateProvisioningJobParams) (ProvisioningJob, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteOrderItems(ctx context.Context, orderID uuid.UUID) error
	DeletePlan(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	FailJob(ctx context.Context, arg FailJobParams) (ProvisioningJob, error)
	GetCustomerProfile(ctx context.Context, userID uuid.UUID) (CustomerProfile, error)
	GetDisputeByID(ctx context.Context, id uuid.UUID) (Dispute, error)
	GetDisputeByStripeID(ctx context.Context, stripeDisputeID pgtype.Text) (Dispute, error)
	GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error)
	GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByStripeIntent(ctx context.Context, stripePaymentIntentID pgtype.Text) (Payment, error)
	GetPaymentByStripeSession(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (Payment, error)
	GetPaymentEventByStripeID(ctx context.Context, stripeEventID string) (PaymentEvent, error)
	GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error)
	GetPlanBySlug(ctx context.Context, slug string) (Plan, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProvisioningJobByID(ctx context.Context, id uuid.UUID) (ProvisioningJob, error)
	GetRefundByID(ctx context.Context, id uuid.UUID) (Refund, error)
	GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	ListActiveProducts(ctx context.Context) ([]Product, error)
	ListAllDisputes(ctx context.Context, arg ListAllDisputesParams) ([]Dispute, error)
	ListAllInvoices(ctx context.Context, arg ListAllInvoicesParams) ([]Invoice, error)
	ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]Order, error)
	ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error)
	ListAllPlans(ctx context.Context, arg ListAllPlansParams) ([]Plan, error)
	ListAllProducts(ctx context.Context, arg ListAllProductsParams) ([]Product, error)
	ListAllRefunds(ctx context.Context, arg ListAllRefundsParams) ([]Refund, error)
	ListAllServices(ctx context.Context, arg ListAllServicesParams) ([]Service, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListExpiringServices(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Service, error)
	ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error)
	ListInvoicesByUser(ctx context.Context, arg ListInvoicesByUserParams) ([]Invoice, error)
	ListJobsByService(ctx context.Context, serviceID uuid.UUID) ([]ProvisioningJob, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error)
	ListPendingJobs(ctx context.Context, limit int32) ([]ProvisioningJob, error)
	ListPlansByProduct(ctx context.Context, productID uuid.UUID) ([]Plan, error)
	ListRefundsByPayment(ctx context.Context, paymentID uuid.UUID) ([]Refund, error)
	ListRetryableJobs(ctx context.Context, limit int32) ([]ProvisioningJob, error)
	ListServicesByUser(ctx context.Context, arg ListServicesByUserParams) ([]Service, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	MarkInvoicePaid(ctx context.Context, id uuid.UUID) (Invoice, error)
	MarkPaymentEventFailed(ctx context.Context, arg MarkPaymentEventFailedParams) error
	MarkPaymentEventProcessed(ctx context.Context, id uuid.UUID) error
	StartJob(ctx context.Context, id uuid.UUID) (ProvisioningJob, error)
	UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (Dispute, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (ProvisioningJob, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (Refund, error)
	UpdateServiceExpiry(ctx context.Context, arg UpdateServiceExpiryParams) error
	UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertCustomerProfile(ctx context.Context, arg UpsertCustomerProfileParams) (CustomerProfile, error)
}

var _ Querier = (*Queries)(nil)
