// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refunds_disputes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDispute = `-- name: CreateDispute :one
INSERT INTO disputes (payment_id, stripe_dispute_id, amount, reason, status, evidence_due_by)
VALUES ($1, $2, $3, $4, 'needs_response', $5)
RETURNING id, payment_id, stripe_dispute_id, amount, reason, status, evidence_due_by, created_at, updated_at
`

type CreateDisputeParams struct {
	PaymentID       uuid.UUID          `json:"payment_id"`
	StripeDisputeID pgtype.Text        `json:"stripe_dispute_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Reason          pgtype.Text        `json:"reason"`
	EvidenceDueBy   pgtype.Timestamptz `json:"evidence_due_by"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, createDispute,
		arg.PaymentID,
		arg.StripeDisputeID,
		arg.Amount,
		arg.Reason,
		arg.EvidenceDueBy,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeDisputeID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.EvidenceDueBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (payment_id, stripe_refund_id, amount, reason, status, created_by)
VALUES ($1, $2, $3, $4, 'pending', $5)
RETURNING id, payment_id, stripe_refund_id, amount, reason, status, created_by, created_at, updated_at
`

type CreateRefundParams struct {
	PaymentID      uuid.UUID      `json:"payment_id"`
	StripeRefundID pgtype.Text    `json:"stripe_refund_id"`
	Amount         pgtype.Numeric `json:"amount"`
	Reason         pgtype.Text    `json:"reason"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.PaymentID,
		arg.StripeRefundID,
		arg.Amount,
		arg.Reason,
		arg.CreatedBy,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeRefundID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDisputeByID = `-- name: GetDisputeByID :one
SELECT id, payment_id, stripe_dispute_id, amount, reason, status, evidence_due_by, created_at, updated_at FROM disputes WHERE id = $1
`

func (q *Queries) GetDisputeByID(ctx context.Context, id uuid.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDisputeByID, id)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeDisputeID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.EvidenceDueBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDisputeByStripeID = `-- name: GetDisputeByStripeID :one
SELECT id, payment_id, stripe_dispute_id, amount, reason, status, evidence_due_by, created_at, updated_at FROM disputes WHERE stripe_dispute_id = $1
`

func (q *Queries) GetDisputeByStripeID(ctx context.Context, stripeDisputeID pgtype.Text) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDisputeByStripeID, stripeDisputeID)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeDisputeID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.EvidenceDueBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, payment_id, stripe_refund_id, amount, reason, status, created_by, created_at, updated_at FROM refunds WHERE id = $1
`

func (q *Queries) GetRefundByID(ctx context.Context, id uuid.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByID, id)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeRefundID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDisputes = `-- name: ListAllDisputes :many
SELECT id, payment_id, stripe_dispute_id, amount, reason, status, evidence_due_by, created_at, updated_at FROM disputes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllDisputesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllDisputes(ctx context.Context, arg ListAllDisputesParams) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listAllDisputes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dispute{}
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.StripeDisputeID,
			&i.Amount,
			&i.Reason,
			&i.Status,
			&i.EvidenceDueBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRefunds = `-- name: ListAllRefunds :many
SELECT id, payment_id, stripe_refund_id, amount, reason, status, created_by, created_at, updated_at FROM refunds ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllRefundsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllRefunds(ctx context.Context, arg ListAllRefundsParams) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listAllRefunds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.StripeRefundID,
			&i.Amount,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsByPayment = `-- name: ListRefundsByPayment :many
SELECT id, payment_id, stripe_refund_id, amount, reason, status, created_by, created_at, updated_at FROM refunds WHERE payment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRefundsByPayment(ctx context.Context, paymentID uuid.UUID) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listRefundsByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.StripeRefundID,
			&i.Amount,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisputeStatus = `-- name: UpdateDisputeStatus :one
UPDATE disputes SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, payment_id, stripe_dispute_id, amount, reason, status, evidence_due_by, created_at, updated_at
`

type UpdateDisputeStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status DisputeStatus `json:"status"`
}

func (q *Queries) UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, updateDisputeStatus, arg.ID, arg.Status)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeDisputeID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.EvidenceDueBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRefundStatus = `-- name: UpdateRefundStatus :one
UPDATE refunds SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, payment_id, stripe_refund_id, amount, reason, status, created_by, created_at, updated_at
`

type UpdateRefundStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status RefundStatus `json:"status"`
}

func (q *Queries) UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (Refund, error) {
	row := q.db.QueryRow(ctx, updateRefundStatus, arg.ID, arg.Status)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StripeRefundID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
