// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelService = `-- name: CancelService :exec
UPDATE services SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) CancelService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelService, id)
	return err
}

const countServicesByUser = `-- name: CountServicesByUser :one
SELECT COUNT(*) FROM services WHERE user_id = $1
`

func (q *Queries) CountServicesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countServicesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, metadata)
VALUES ($1, $2, $3, 'pending', $4, $5, $6, $7)
RETURNING id, user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, cancelled_at, metadata, created_at, updated_at
`

type CreateServiceParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	OrderItemID uuid.UUID          `json:"order_item_id"`
	PlanID      uuid.UUID          `json:"plan_id"`
	Hostname    pgtype.Text        `json:"hostname"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Metadata    json.RawMessage    `json:"metadata"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.UserID,
		arg.OrderItemID,
		arg.PlanID,
		arg.Hostname,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderItemID,
		&i.PlanID,
		&i.Status,
		&i.Hostname,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, cancelled_at, metadata, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderItemID,
		&i.PlanID,
		&i.Status,
		&i.Hostname,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, cancelled_at, metadata, created_at, updated_at FROM services ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllServicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllServices(ctx context.Context, arg ListAllServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listAllServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderItemID,
			&i.PlanID,
			&i.Status,
			&i.Hostname,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringServices = `-- name: ListExpiringServices :many
SELECT id, user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, cancelled_at, metadata, created_at, updated_at FROM services WHERE status = 'active' AND expires_at <= $1 ORDER BY expires_at ASC
`

func (q *Queries) ListExpiringServices(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Service, error) {
	rows, err := q.db.Query(ctx, listExpiringServices, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderItemID,
			&i.PlanID,
			&i.Status,
			&i.Hostname,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByUser = `-- name: ListServicesByUser :many
SELECT id, user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, cancelled_at, metadata, created_at, updated_at FROM services WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListServicesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListServicesByUser(ctx context.Context, arg ListServicesByUserParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderItemID,
			&i.PlanID,
			&i.Status,
			&i.Hostname,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceExpiry = `-- name: UpdateServiceExpiry :exec
UPDATE services SET expires_at = $2, updated_at = NOW() WHERE id = $1
`

type UpdateServiceExpiryParams struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateServiceExpiry(ctx context.Context, arg UpdateServiceExpiryParams) error {
	_, err := q.db.Exec(ctx, updateServiceExpiry, arg.ID, arg.ExpiresAt)
	return err
}

const updateServiceStatus = `-- name: UpdateServiceStatus :one
UPDATE services SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, order_item_id, plan_id, status, hostname, ip_address, expires_at, cancelled_at, metadata, created_at, updated_at
`

type UpdateServiceStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status ServiceStatus `json:"status"`
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceStatus, arg.ID, arg.Status)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderItemID,
		&i.PlanID,
		&i.Status,
		&i.Hostname,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
